### ISSUE TITLE
[Feature Req] Limit LORA influence when using MASK or AREA

### ISSUE THREAD

**Issue by Lancer1408** [asagi4/comfyui-prompt-control#10]
Hello and thanks for making these nodes! 
They are really interesting and I've been playing around with them.

So I'm testing along the MASK and AREA modes, and I've come to wonder if its already possible to limit the influence of a lora only to the MASK or AREA regions without the lora baking the other parts of the generation.

If not, could it be possible to implement something similar to this?
As on Auto1111 the extensions [Lora Masks](https://github.com/lifeisboringsoprogramming/sd-webui-lora-masks) and [Composable Lora](https://github.com/a2569875/stable-diffusion-webui-composable-lora) achieve the desired effect of only allowing a lora to work in a specific region without frying the rest of the generation.

Thanks a lot for your time!

**Comment by Lancer1408** [comment]
rip, tho I kinda expected it to be really hard to implement, as the only node that does something similar is one of the Impact pack nodes, but that one generates over an already existing image.

I guess the messy code of Auto1111 allowed the extensions I linked possible lol

Thanks a lot!

**Comment by asagi4** [comment]
@Lancer1408 There is probably some way to do this, if I reimplement LoRAs as a transformer patch or something, but it's going to take more than one evening of study to figure things out, which might mean I'll have it done next week or next decade, given that my motivation to work on new features is completely unpredictable. :-)

**Comment by Lancer1408** [comment]
@asagi4 lol no need to hurry, just wanted to know if it was possible, tho masking loras is a really cool concept that I would be cool to see on Comfy.

Totally, I'm sure it is indeed possible, but seems to be quite hard to implement without messing too much with the ksamplers and lora forwards.
