### ISSUE TITLE
Does Prompt control work with SDXL? 

### ISSUE THREAD

**Issue by Takeover713** [asagi4/comfyui-prompt-control#17]
Hello, i was wondering if prompt control work with SDXL if it doesnt its fine im just wondering if i have to set it up differently. 
i was trying to use prompt control to be able to use the lora loading using the prompt. 
it works great for SD 1.5 models i love it its amazing. i do not get any errors and it seems to load the loras fine.
but i get an error message when trying to use the same set up with SDXL. 
ill put screen shot of the error im getting and how i have the nodes hooked up.  thank you.

![Screenshot 2023-12-13 023337](https://github.com/asagi4/comfyui-prompt-control/assets/44397569/295a6ff5-60a6-4301-8744-23c25ea324db)
![Screenshot 2023-12-13 022530](https://github.com/asagi4/comfyui-prompt-control/assets/44397569/1f6edcb4-42b7-4f01-905c-e271a254d97a)

**Comment by asagi4** [comment]
It partially works, but I don't run SDXL that often, so it might have a bug.

Can you test with a simpler workflow? The problem might be an interaction with the other nodes in your workflow, so first test if the simplest possible SDXL workflow functions and then try adding nodes to see where it breaks.

**Comment by Kaharos94** [comment]
![workflow (2)](https://github.com/asagi4/comfyui-prompt-control/assets/80826189/8cbf2c5f-1edd-4106-9cf1-d1149420344c)
Well, it breaks on a the default workflow - same setup worked with 1.5.

**Comment by WeeBull** [comment]
I think some recent changes broke things. Not sure if it's in this package or changes in ComfyUI.

Certainly worked with SDXL a couple of weeks ago.

**Comment by Takeover713** [comment]
yea breaks on basic workflow with SDXL. works fine with 1.5. <3

**Comment by asagi4** [comment]
Something has changed with SDXL CLIP enconding that's incompatible in some way.

Unfortunately, I don't really have any ideas as to why things aren't working; the "pooled" output from the SDXL CLIP seems to somehow results in shape errors, but to be completely honest I don't know what that even is.

**Comment by asagi4** [comment]
The shape mismatch in question is
```
flat.shape=torch.Size([1, 1536]) clip_pooled.shape=torch.Size([1, 77, 2048])
```
but I don't know where those sizes come from; 1 is probably the batch size and 77 is the text encoder chunk size, but 1536 and 2048 don't seem to match any input parameter anywhere.

**Comment by asagi4** [comment]
Derp, the reason was that I applied (optional) noise to the pooled with the following code: `pooled = apply_noise(cond, ...)` instead of `apply_noise(pooled, ...)`

Should be fixed now.

**Comment by Takeover713** [comment]
Thank you for your amazing work on this custom node. I greatly appreciate it.
