### ISSUE TITLE
`BREAK` support

### ISSUE THREAD

**Issue by VelvetToroyashi** [asagi4/comfyui-prompt-control#19]
There is already `AND` support, which is equivalent to `ConditioningAverage`, however there is no `BREAK` support, which would map to `ConditioningConcat`. Furthermore, because of how Comfy handles this, this node cannot be combined with `ConditioningConcat` because `AND` makes the prompt return multiple conds, of which only the first is taken.

**Comment by asagi4** [comment]
there is BREAK though, but it works on the token level meaning whenever there is a BREAK in the prompt it'll get padded to the closest 77 token multiple before continuing tokenization, and that result is then encoded into a cond; as far as I understood, that's how it works in A1111 too. I'm pretty sure it has the same effect as ConditioningConcat.

**Comment by VelvetToroyashi** [comment]
Oh, huh. When I initially looked through the code I only saw the support for `AND`--

I initially mentioned that I didn't see it mentioned in the README either, however unfortunately I appear to be as blind as ever, and read right over it. Apologies, and thanks for the useful node!
