### ISSUE TITLE
Explain the purpose of multiple passes in the example repo please

### ISSUE THREAD

**Issue by ghostsquad** [asagi4/comfyui-prompt-control#20]
Can you explain the purpose of a "2-pass" workflow as in the example posted in the Readme please?

**Comment by asagi4** [comment]
@ghostsquad What's unclear? In the example, it's just showing off the tag and timestep-based filtering for a highres/upscale pass. It's optional, so if you don't need it, you can just leave it out.

**Comment by ghostsquad** [comment]
Ya, sorry. Maybe it was a dumb question 😅. I didn't realize that "second pass" meant upscaling. Thanks for the explanation!
