### ISSUE TITLE
Example Workflow Doesn't Load

### ISSUE THREAD

**Issue by lstyls** [asagi4/comfyui-prompt-control#21]
Quite possibly I am doing something stupid, but I can't get the example workflow to load on latest ComfyUI + latest comfyui-prompt-control.

Repro:
- Launch ComfyUI with commit checkout `1b103e0` and `custom/nodes/comfyui-prompt-control` commit checkout `50a28bb`.
- Try loading example workflow from https://github.com/asagi4/comfyui-prompt-control/blob/master/workflows/example.json

Expected Behavior:
- Example workflow loads

Experienced Behavior:
- ComfyUI UI remains blank, no error message in browser or console

**Comment by asagi4** [comment]
I can't reproduce this with my ComfyUI + Firefox; the workflow loads just fine. Do you see any messages in the browser console?

Did you make sure to download the raw JSON file instead of accidentally downloading Github's HTML render of it?

**Comment by asagi4** [comment]
Actually, I should probably link directly to the raw download from the README to make that mistake less likely...

**Comment by lstyls** [comment]
You're right, I tried Firefox and it loaded fine. Also loads fine under a clean Chrome install - mine was a bit stale, so it was probably some issue specific to my crufty chrome installation. I should have thought to try Firefox before opening an issue, my bad.

Thanks for a really useful extension!
