### ISSUE TITLE
Example SDXL workflow

### ISSUE THREAD

**Issue by ghostsquad** [asagi4/comfyui-prompt-control#23]
Please provide an example SDXL workflow. I'm trying to integrate SDXL, and I'm having some trouble understanding what changes I need to use these nodes. Thanks!

**Comment by ghostsquad** [comment]
Cool. So the node has some way to detect if the model is an SDXL model?

**Comment by asagi4** [comment]
ComfyUI does the model loading. My nodes don't care at all about what the model is, but it does have some SDXL-specific logic in the conditioning encoder since SDXL conds have some extra features that don't exist in SD 1.5

**Comment by ghostsquad** [comment]
thanks for the explanation
