### ISSUE TITLE
Embedding alt syntax does not work

### ISSUE THREAD

**Issue by ahoeppner** [asagi4/comfyui-prompt-control#24]
Thanks for the hard work making this project, it's amazing.

I noticed when I tried to use the alt syntax for embeddings, `<emb:xyz>`, i would be returned:
```
[ERROR] PromptControl: Prompt editing parse error: Error trying to process rule "embedding":

'str' object has no attribute 'value'
```

I was able to fix the error by modifying the `embedding()` function to:

```
def embedding(self, args):
        return "embedding:" + args[0]
```

I believe omitting the `.value` property works because the function is trying to access a value attribute on a string object, which does not exist. I don't know if this is the correct fix, or if the `embedding()` function is intended to be passed something else other than a string.

EDIT: embedding weighting doesn't work with my solution, but doing like `<emb:xyz:0.5>` doesn't seem to work for me with the deployed version either, so I'm not sure what the right approach is.

**Comment by asagi4** [comment]
`<emb:foo:N>` has never worked, though maybe I should make it work because it is easy to confuse given the LoRA syntax.
