### ISSUE TITLE
Support folder when loading lora?

### ISSUE THREAD

**Issue by dchatel** [asagi4/comfyui-prompt-control#29]
In parser.py, line 29 we can see this:
```
FILENAME: /[^<>:\/\\]+/
```
Which actually prevents the use of folders for arranging loras.
Maybe change it to `FILENAME: /[^<>:]+/` ?
Is there any reason for filtering slashes and backslashes?

**Comment by asagi4** [comment]
The node will find LoRAs in subdirs by just using the filename (without its extension), though if you have two LoRAs with the same name it'll pick the first one it finds.

I might relax the requirement and allow specifying directories, but I haven't had a need for that myself so I haven't implemented it.
