### ISSUE TITLE
If the Lora file name has . symbol, it will show that Lora was not found and Lora cannot be used.

### ISSUE THREAD

**Issue by yeungmozhu** [asagi4/comfyui-prompt-control#31]
If the Lora file name has the . symbol, it will show Lora not found and cannot use Lora. 
For example, the "PAseerGoldenWindSD1.5-V1.safetensors" file, when I type <lora:PAseerGoldenWindSD1.5-V1:0.5>, it will show `PromptControl: Lora PAseerGoldenWindSD1.5-V1 not found.`
When I change "PAseerGoldenWindSD1.5-V1.safetensors" to "PAseerGoldenWindSD15-V1.safetensors" and type <lora:PAseerGoldenWindSD15-V1:0.5> it works!

**Comment by asagi4** [comment]
I think this happens because it detects the stuff after the first dot as an extension and ignores it.

I'll fix this later today.
