### ISSUE TITLE
When using Lora's schedule syntax, the second pass has no effect on any Lora effects

### ISSUE THREAD

**Issue by sato68885345** [asagi4/comfyui-prompt-control#33]
Hello. Your node was great enough to pull me back to ComfyUI from Forge.

I have a problem with the notation,
I noticed that when using Lora's schedule syntax, the first pass of the example.json worked as expected, but the second pass did not cause any LoRA effect itself.

I'm having difficulty with the example,
We adapted LoRA to display a realistic woman against a cartoon type model (e.g. animagine) with extreme settings.
[\<lora:realmodel_xl_v01:1.5:1.6\>::0.99]

In this case, 99% of the time, the LoRA should result in a realistic woman due to the LoRA effect, and the animated woman effect should only work on the remaining 1%.

However, the result is that the First Pass is a realistic woman as described, but the Second Pass does not have the 99% realistic woman effect at all and produces an animated woman.

This also occurs with the original topology other than example.json.
![2024-03-10 22 08 03](https://github.com/asagi4/comfyui-prompt-control/assets/144400210/68f00abf-d3f9-4298-b612-e7c7188217b2)

**Comment by asagi4** [comment]
Sounds like you already figured it out, but I suspect this was because of the filtering applied to the schedule before the second pass.

The example workflow is made that way to show what you can do with filtering and tags.
