### ISSUE TITLE
SamplerCustom is referencing cfg as the step count when scheduling Lora

### ISSUE THREAD

**Issue by pyomyofiro** [asagi4/comfyui-prompt-control#34]
SamplerCustom is referencing cfg as the step count when scheduling Lora
![rapture_20240319225456](https://github.com/asagi4/comfyui-prompt-control/assets/127836837/e19dd43b-0692-41ae-8059-6c08e87c1d68)
![rapture_20240319225605](https://github.com/asagi4/comfyui-prompt-control/assets/127836837/266cfe88-1130-453d-b17e-257629249274)
![rapture_20240319225649](https://github.com/asagi4/comfyui-prompt-control/assets/127836837/4faeba9e-fcf2-4724-898e-eb18ea9b734d)
![rapture_20240319225725](https://github.com/asagi4/comfyui-prompt-control/assets/127836837/a33a6e29-792e-4e75-8baf-4e385601be1e)

When I want to use SamplerCustom, I am manually altering this part to the actual step count value.
![rapture_20240319225932](https://github.com/asagi4/comfyui-prompt-control/assets/127836837/da20c8a2-d951-4a69-9cbf-796048a1b54b)

**Comment by asagi4** [comment]
Hm. Looks like the sample_custom function needs a completely different hijack, since the steps value isn't even available.

I never use the sampler nodes, so I never noticed this.

**Comment by asagi4** [comment]
The above commit isn't a perfect fix since some samplers discard the penultimate sigma, but it's close enough that I'll consider this issue fixed.
