### ISSUE TITLE
Minimum `lark` version?

### ISSUE THREAD

**Issue by DrJKL** [asagi4/comfyui-prompt-control#35]
I kept getting `float() argument must be a string or a real number, not 'Tree'` earlier, had to update lark to 1.1.9 from 1.1.7.
Haven't gone back to see if 1.1.8 also would have worked.

Do you know what the minimum version should be in requirements?

**Comment by asagi4** [comment]
I seem to have have 1.1.2 installed myself, so I maybe 1.1.7 just had a bug.

**Comment by asagi4** [comment]
I added a version requirement to `requirements.txt`, I think if it works with 1.1.9, that should be enough for this issue.
