### ISSUE TITLE
[FR] Custom mask support

### ISSUE THREAD

**Issue by SRagy** [asagi4/comfyui-prompt-control#44]
**Describe what's missing**
A way to use nonrectangular masks.

**Additional context**
I know it might seem slightly against the ethos of the extension, however, it would be convenient to be able to feed custom masks (e.g. hand drawn ones) into a node. Unless I'm missing something, the existing syntax limits to rectangular masks and specification is a touch clunky. If masks were taken as input, then they could be activated within the text [perhaps with a syntax like (MASK:mask1)]

This would provide a similar functionality to Automatic1111's regional prompter extension's custom masks option.

**Comment by asagi4** [comment]
That's not a terrible idea. it should be pretty easy to implement a `ScheduleToCondMasked` node with that functionality.

**Comment by asagi4** [comment]
I added an experimental implementation.

It's very lightly tested so I'm not documenting it yet, but please give it a try. Just use PCScheduleAddMasks to attach masks to the prompt schedule object and then in the prompt use IMASK(index, weight, combineop) to refer to them. (the defaults are 0, 1.0, multiply if not specified). The mask indexing starts from 0.

The node allows adding up to 4 masks in one go (they're all optional), but you can use it as many times as you need; it'll just extend the mask list.

**Comment by SRagy** [comment]
That was super fast, thanks! I will get back to you as soon as I've had a chance to test it, which will be some time in the next two days.
