### ISSUE TITLE
[FR] Improved examples

### ISSUE THREAD

**Issue by rafstahelin** [asagi4/comfyui-prompt-control#45]
**Describe what's missing**
A more visual guide for entry level people. I am really having a hard time understanding how scheduling lora's work here. More specific breakdowns in the readme, with particular examples would really help. 
Not expecting youtube tutorial but maybe from concrete examples with image and values in the workspace would be super welcome. Very keen to learn

**Additional context**

**Comment by asagi4** [comment]
Can you describe what you find confusing about LoRA scheduling? It works the exact same way as prompt scheduling.

At every step, the prompt is "expanded" to include only the parts that are active during that step, and if a LoRA is mentioned in the prompt, it gets applied during that step.

**Comment by PurplefinNeptuna** [comment]
can I barge in?
I want to put `fire` in prompt after 0.2 progress
I usually did it using `[:fire:0.2]` in A1111, but it seems to not working here, fire already influenced the result from start. what's the prompt should be?

**Comment by asagi4** [comment]
@PurplefinNeptuna That would be just `[fire:0.2]`. I guess I could make the other form work too for consistency but I don't like touching the lark grammar because changing it can sometimes cause weird side-effects.

The range in `INT` is the steps between which the interpolation happens.

**Comment by DrJKL** [comment]
I've also done `[_:fire:0.2]`
