### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Utoko** [asagi4/comfyui-prompt-control#46]
**Describe the bug**
I updated ComfyUI and it seemed that is broke the node. 

**To Reproduce**
Run Prompt scheduler [ Dog:cat:0.35]
The example workflow doesn't work anymore.

"Error occurred when executing PromptToSchedule:

float() argument must be a string or a real number, not 'Tree'
"

**Comment by asagi4** [comment]
Please make sure that you have a supported version of lark installed. That looks like the bug that some people have reported if their version of lark is too old. `pip install -U lark` in the virtualenv will update the package.

**Comment by Utoko** [comment]
Thanks I made sure 
`Requirement already satisfied`

It worked fine ->updated comfyUI + Addons and now I get the error.  M2 Macbook, but I guess it is a me problem.
I thought it would be a general issue.

**Comment by JoyfulTemplate** [comment]
@Utoko I think  ComfyUI update process may mess up some dependencies, my lark version shows 1.1.9 in `pip list` but it's actually not. I fixed it using `pip install --upgrade --force "lark>=1.1.9"`.

**Comment by Utoko** [comment]
That worked! Thanks
