### ISSUE TITLE
[FR] Programmatic Features  (without needing special syntax)

### ISSUE THREAD

**Issue by ghostsquad** [asagi4/comfyui-prompt-control#48]
**Describe what's missing**
I'd like to extend these nodes and provide alternative methods that aren't as complex/error prone as writing a string with special syntax to do all the various features like scheduling, alternating, sequences etc. At first I thought about _generating_ the string providing the user input of tokens, but then realized that I'd likely run into similar issues with syntax getting messed up. This isn't as much of a feature request as it is a dialogue for how might I contribute to this in a more programmatic way, and avoid "special strings" and string parsing? Thanks for your time!

A very simple example is a node that takes 2 strings, and either a slider or a number, and either emits `[cat|dog:0.05]` or rather, if I contributed directly to this repo, a way to take that information, and "build up" the prompt/conditioning, before eventually "finalizing" it. (The Builder Pattern).

**Comment by ghostsquad** [comment]
Thanks! I'll keep reading up on `PROMPT_SCHEDULE` and post a PR to discuss.

**Comment by asagi4** [comment]
Closing this, not really applicable anymore
