### ISSUE TITLE
[FR] Flux Support?

### ISSUE THREAD

**Issue by ghostsquad** [asagi4/comfyui-prompt-control#57]
Has this been tested to work with Flux?

**Comment by asagi4** [comment]
I had a local modification to make flux not error out.

The support isn't complete; prompt styles don't work with flux, but with the latest commit on the master branch, you should at least be able to run the node with flux's CLIP.

As for LoRA loading, I have no idea; I barely have enough VRAM to run flux at all, so I haven't tested LoRAs.

**Comment by DrJKL** [comment]
Yeah, Flux LoRAs cause an OOM for me pretty frequently.

**Comment by asagi4** [comment]
This is likely to improve as ComfyUI patch hooks PR gets merged. Follow #63 and check out the patch_hooks branch to try out the new nodes.

**Comment by asagi4** [comment]
I just merged the new nodes to master since ComfyUI merged the patch mechanism. Please go test with them.

**Comment by asagi4** [comment]
That's good to hear. I think I'll resolve this issue then
