### ISSUE TITLE
Just looking to use AND?

### ISSUE THREAD

**Issue by Charuru** [asagi4/comfyui-prompt-control#6]
I'm pretty new to comfyui so sorry if this a dumb question.

My understanding is that the AND keyword separates the prompt such that the two parts won't interfere with one another. Is that the case or am I misunderstanding?

If I want to get that functionality do I need to still use the scheduling nodes or should it work in the regular CLIP text encode upon install?

**Comment by asagi4** [comment]
You'll need the scheduling nodes. And the AND keyword doesn't really do anything very special. it splits the prompt and combines them (with optional weights) like the ConditioningAverage node in ComfyUI, so it's basically just a shortcut for that node.

**Comment by Charuru** [comment]
Thanks!
