### ISSUE TITLE
[BUG] "ScheduleToModel" swithes loaded models

### ISSUE THREAD

**Issue by miasik** [asagi4/comfyui-prompt-control#61]
I use a workflow where both "Prompt control" and "Dare merge" are implemented. In my workflow there are three steps — models merging, a small preview and a latent upscale.
https://github.com/54rt1n/ComfyUI-DareMerge

Using different models is really useful to see the difference
1st model - any flat anime, I use https://civitai.com/models/210981/nuke-colormax-anime
2nd — any photo, I use https://civitai.com/models/565375?modelVersionId=671909
both are SD15 for speed

When the merging output is connected directly to the preview and the upscale Ksamplers it works correctly — I see a typical 50/50 merge(as for cartoon+photo) in the preview window and the same in the upscaled window.

When the merging output is connected to the "Prompt control" input and the Ksamplers are connected to the "Prompt control" output it renders different images. The preview is correct, it's still the same 50/50 merge, but the upscaled one is wrong. It looks like the preview image gets upscaled by unmodified "Base" flat cartoon model.

[SD15 Dare wrong.json](https://github.com/user-attachments/files/17174881/SD15.Dare.wrong.json)
[SD15 Dare working.json](https://github.com/user-attachments/files/17174882/SD15.Dare.working.json)

If you see a flat cartoon image in the preview, change the seed to push the merging part to regenerate a model.

**Comment by asagi4** [comment]
Without looking into it, it seems prompt control might be dropping other patches from the model when it runs unpatch to reset LoRAs.

**Comment by miasik** [comment]
> Without looking into it, it seems prompt control might be dropping other patches from the model when it runs unpatch to reset LoRAs.

Is there a chance that you will take a look into the issue?

**Comment by asagi4** [comment]
I pushed a commit into another branch (issue_61) that I think might fix this, but it's currently completely untested. Feel free to try it out if it helps.

**Comment by asagi4** [comment]
I'm unlikely to work on this more with ScheduleToModel since #63 should offload all the weight shuffling to Core ComfyUI, so keep an eye on that.

**Comment by asagi4** [comment]
This should now be fixed by using `PCLoraHooksFromSchedule`. I will not fix the old nodes.
