### ISSUE TITLE
[FR] SD3.5 Support

### ISSUE THREAD

**Issue by tncrdn** [asagi4/comfyui-prompt-control#62]
Does Prompt Control work with Stable Diffusion 3.5 Large?

**Comment by asagi4** [comment]
I haven't tested. I don't really have the hardware to use SD3.5L

Chances are when the patch hook improvements land in ComfyUI, I'll be able to write a version of prompt control that'll just work with most things.

If you hit any bugs, report them, and I'll see what I can do.
