### ISSUE TITLE
[FR] Efficient Schedulable LoRAs

### ISSUE THREAD

**Issue by catboxanon** [asagi4/comfyui-prompt-control#63]
From my understanding, the current implementation has to hijack and re-patch the model for each schedule change, but once https://github.com/comfyanonymous/ComfyUI/pull/5583 is merged upstream, this will be possible to be remedied and implemented in a more efficient manner. Creating this feature request in hopes to track when this has been implemented.

In particular, I'm hoping this upstream change could make the LoRA switch application method (https://maszhongming.github.io/Multi-LoRA-Composition/) more efficient to use.

**Comment by asagi4** [comment]
I already have a basic implementation using the hook system; it's not really much more efficient than what the nodes do currently, but it does avoid monkey patching. In my personal use, it doesn't work properly when using onediff for acceleration either, so that's something I'll have to solve (I like the +70% perf I get from onediff too much to just give it up)

Using the new mechanism I'll probably have to throw away support for some features like non-comfyui weight interpretations at least until I can figure out a good way to reimplement them.

**Comment by Kosinkadink** [comment]
I have not had a chance to look at OneDiff or custom weight interpretations in ComfyUI. If you could identify pain points for getting one or the other to work in ComfyUI, please let me know so I can work on another PR that can make it not be a massive endeavor! The non-comfyui weights is likely the place to start.

From my experience with AnimateDiff-Evolved and Advanced-ControlNet, there's a lot of custom nodes that could have a clean implementation, but only if ComfyUI properly exposed a way to edit something specific at runtime. I want to help mediate turning "hacks" into "features". Not only does it help with node development, but also let's more nodes co-exist properly.

**Comment by asagi4** [comment]
@Kosinkadink yeah the onediff comfy nodes basically replace the torch diffusion_model object with one built with a mostly-compatible library that is faster and has a lot of monkeypatching going on; it's pretty amazing it works at all to be honest and it has some limitations, but the speedup is pretty significant and it doesn't take half an hour to compile like TensorRT and what have you.

As for weight interpretations, the first problem I'm seeing is that `cond_stage_model.encode_token_weights` in some cases can actually call *multiple* different text encoder models and then usually just combines the results before any custom implementation can do anything, if for example they'd like to do some math with the different tensors before combining things. 

Currently the implementations seem to just completely redo all the logic of text encoding so they wouldn't really work together well with the new hook scheduling before they reimplement at least the logic in `encode_from_tokens_scheduled`

Still, having the new hook system is already a massive improvement over existing hacks, so these are relatively minor problems that can be solved once things get merged.

**Comment by asagi4** [comment]
I think I figured out a pretty neat way to keep advanced encoding working, so I pushed a *very* rough implementation in a new branch.

I think I need to change the node interface to suit the new mechanism better, currently it's just enough to make things kinda work.

**Comment by asagi4** [comment]
The new nodes are now merged to master.

They're still not quite complete, but all development effort is going to be around them going forward; I might even release a 2.0 at some point which removes the old nodes completely, depending on how much work it is to keep them working at all.

**Comment by asagi4** [comment]
I'm creating new issues for missing features in the new implementation, so I'll close this one
