### ISSUE TITLE
[FR] Suggestion for improving syntax documentation

### ISSUE THREAD

**Issue by DrMechanica** [asagi4/comfyui-prompt-control#66]
This just a request for a little clearer documentation of the scheduling syntax. Maybe A1111 docs cover this in more depth, but I think it'd be handy to have here, too. 
I was really struggling with the basic syntax of scheduling, finding it a bit inconsistent and confusing, due mainly to the empty parameter shorthand (`[a:0.5] == [a::0.5]`), default `0` start, and my thinking about the parameter/percentage relationship as reading left to right. For example in `[cat:dog:0.3]` the first percentage appears to define the end point of parameter 1, while in `[cat:dog:0.3, 0.7]` the first percentage defines the start point of parameter 1, and the same in `[cat:0.3, 0.7]`. BUT in `[cat:0.3]` the first percentage appears to define the end point of parameter 1 again. This was throwing me into a mess of mental gymnastic IF/THENs when trying to read and interpret prompts ("if more than one percentage is given then percentage 1 defines the start of parameter 1, otherwise it defines the end of parameter 1" type of thinking). 

I propose an even more clearcut explanation on syntax in the documentation, something like: 

> Scheduling blocks should be read right to left, matching the rightmost percentage as the start point of the rightmost prompt segment, and so on. Prompt segments with no corresponding start percentage start at 0.
> 
> `[cat:dog:0.5,0.7]` should be read as `0.7` is the start of `dog`, `0.5` is the start of `cat`.
> `[cat:dog:0.5]` should be read as  `0.5` is the start of `dog`, `0` is the start of `cat`.
> `[cat::0.5]` should be read as `0.5` is the start of nothing, `0` is the start of `cat`. In cases with only one prompt segment like this, the extra extra colon can also be omitted: `[cat:0.5] == [cat::0.5]`. 
> Therefor, `[cat:0.5,0.7] == [cat::0.5,0.7]`, so it should be read as `0.7` is the start of nothing, `0.5` is the start of `cat`.
> `[:cat:0.5]` should be read as `0.5` is the start of `cat`, `0` is the start of nothing.

I don't know if that last line is accurate, actually, I'm just guessing. But I think you get the idea.

Anyway, maybe I'm just slow, but I think some language like this would really help people get their heads around the syntax more easily.

**Comment by asagi4** [comment]
I think you've misunderstood what `[cat:0.5]` does. It isn't shorthand for `[cat::0.5]`; it's equivalent to `[:cat:0.5]` (that the parser doesn't currently handle).

The range syntaxt was added later as a convenience for somewhat common use case of `[[cat:0.3]:dog:0.7]`

**Comment by asagi4** [comment]
I suppose you can think of it as every scheduled expression has a start and an end prompt parameter and a switch point, having an implicit *start* from an empty string if you only give it one parameter, and with range expressions, it's empty until the range begins and the parameters specify the prompt during and after the range.

**Comment by asagi4** [comment]
The documentation has been pretty substantially reworked, so I'm closing this

**Comment by DrMechanica** [comment]
Hmm, ok I guess I finally get it. I really appreciate the updated documentation, it's much clearer now. I think all the special conditional cases really make using this quite confusing to use though. If you're open to it, and I apologize if I'm overreaching here, I think a reworking of this system sometime in the future to improve consistency and predictability of syntax would be very helpful. 

I'm realizing as I type this, this syntax expects a maximum of two parameters to switch between, and either a single switch percentage or what you're calling a range but operates more like two different switch points. What I'm about to suggest would probably be a ground up overhaul, and definitely ruin all legacy workflows, but I think ultimately what would work better would be moving to range type scheduling exclusively, allowing as many parameters and switch points as desired, with consistent implicit defaults, i.e. 0 start unless explicitly defined, or defined start if that's your preference. 

Right now if I want: `dog` until `0.35`, `cat`  until `0.5`, then nothing until `1`, I have to mentally set a divide point between 0 and 1, in this case `0.35` (`dog` from `0` to `0.35`, then something until `1`), then use a nested expression in the second half to again divide `0` to `1` at `0.7`, understanding it will be masked by the parent expression (`cat` from `0` to `0.7` then nothing until `1`,  but `0` to `0.35` is masked by `dog` in the parent expression), writing it `a [dog:[cat::0.7]:0.35]`. Mentally this requires an overlaying of two different divisions of 0 to 1, with the first masking the second. There's almost a multi-planar geometric element to how one is required to think about this. This could be flattened into a single plane however, if we could write it `a [dog:cat::0.35,0.7]`. This reads as a single chronology, `dog` to `cat` to `nothing` at `0.35` and `0.7` respectively. A `0` start time is implied for the first term, but if this was not desired one could either define it explicitly i.e. `a [dog:cat::0.1,0.35,0.7]`, understanding that by giving as many percentages as there are terms the first percentage will now define the first term's start point. This allows me to read all my change points in the right hand portion of the expression in chronological order instead of having to read them backwards through nested expressions, which I, and possibly others, would find helpful. 

This is quite long and probably too much to implement, so thank you for reading if you made it this far. I don't expect any of these changes, but I thought I'd share them as some food for thought for future development.

**Comment by asagi4** [comment]
Part of the syntax is the way it is because it was originally implemented that way A1111. The syntax optimizes for the most common use cases of "add this to prompt at this point" and "switch from a to b at this point" which is why it's `[add:0.6]` and `[a:b:0.6]`. `[a::0.6]` is just a special case of the latter and `[:a:0.6]` would be too but it just happens to not work because the parser has problems with it. The ranges were a later addition.

For the `[dog:[cat::0.7]:0.35]` use case I agree that it's cumbersome, and that's why the `[SEQ:dog:0.35:cat:0.7]` special syntax exists, and it sounds like it's pretty close to what you're looking for; the steps are just interleaved between prompts instead of at the end.
