### ISSUE TITLE
[BUG] loraspec and not tree error

### ISSUE THREAD

**Issue by Lion-Lawliet** [asagi4/comfyui-prompt-control#67]
**Describe the bug**
I've been using the experimental PCLoraHooksFromSchedule with PromptToSchedule as well hooked to Set CLIP Hooks and I'm getting a weird bug whenever I use the lora prompt: `<lora:LORANAME:1>`

In the terminal, it says:
```
[ERROR] PromptControl: Prompt editing parse error: Error trying to process rule "loraspec":

list index out of range
```

And it seems it wouldn't load the LoRA. Also, there's another bug if I use this format: `[<lora:LORANAME:1>::0.5]`
The system fails to even start, giving me the error:

```
PromptToSchedule

float() argument must be a string or a real number, not 'Tree'
```

Thank you for your time and patience!

**Comment by asagi4** [comment]
I think you might be hitting the mystery bug caused by something that no-one has been able to figure out.

Is your lark version up-to-date? What other things do you have in your virtualenv?

**Comment by asagi4** [comment]
The parser hasn't changed and I can't reproduce this in my environment, so it's likely that this is the same bug that people have been reporting a few times in the past.

I don't know what causes it, but some potential culprits seem to be either a too-old lark version (I have 1.1.9) or some package in the venv that is messing with lark; I've seen some people have "lark-parser" in their venv, and I don't have that.

**Comment by asagi4** [comment]
Yeah that error happens during prompt parsing, so before you even get to Sampling.

Try removing lark-parser from your venv. I have no idea what that package is or why it ever gets installed into people's venvs, but it should not be needed.

**Comment by asagi4** [comment]
@Lion-Lawliet Did you also try removing and reinstalling the lark package?
