### ISSUE TITLE
[BUG] Can't mix embeddings and Cutoff in PCEncodeSchedule

### ISSUE THREAD

**Issue by DrJKL** [asagi4/comfyui-prompt-control#75]
**Before you start**
Verify the following:

- [x] That your ComfyUI is up to date
- [x] That the extension is up to date
- [x] That the issue isn't in the "Known Issues" section in the README

**Describe the bug**
```py
KeyError: tensor([ ... ], dtype=torch.float16)
```

**To Reproduce**
1. Setup a workflow that uses PromptToSchedule and PCEncodeSchedule
2. In the prompt, use both an `embedding:` and `[CUT:...]`
3. Try to run the workflow
4. Worry about how many things run on Python when you see the KeyError in all its obtuse glory.

[promptcontrol_embedding_bug_repro_2.json](https://github.com/user-attachments/files/18055348/promptcontrol_embedding_bug_repro_2.json)

**Expected behavior**
I expected PCEncodeSchedule to behave like ScheduleToCond (see repro workflow)

**Comment by DrJKL** [comment]
Ah, I see you've hit this before. https://github.com/asagi4/comfyui-prompt-control/issues/71

**Comment by DrJKL** [comment]
Just checked, PCEncodeSingle exhibits the same behavior.

**Comment by asagi4** [comment]
hm, I guess I should've tested with embeddings. I don't use them myself so I completely forgot.

Honestly I'm not even sure the reimplemented version of cutoff is correct at all; I had to change its structure quite a bit to get rid of hacks (it runs separately for each text encoder now)

**Comment by asagi4** [comment]
Oh, this might actually be a ComfyUI bug:
```
  File "/home/sd/git/ComfyUI/custom_nodes/comfyui-prompt-control/prompt_control/cutoff.py", line 172, in debug_tokens
    log.debug(" ".join(f"{x[0][0]} {x[1]}" for x in tokenizer.untokenize(tokens) if x[0][0] != tokenizer.end_token))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
untokenize fails with embeddings. I'll add a workaround

**Comment by DrJKL** [comment]
Thanks :-)

Want me to create some test workflows to see how the implementations differ?

**Comment by asagi4** [comment]
@DrJKL I'll take them if you're willing to make some, though depending on the cause of any differences I can't guarantee I'll fix them. Having some comparison workflows for testing would be useful in any case.
