### ISSUE TITLE
[BUG] Alternate LoRAs

### ISSUE THREAD

**Issue by Lion-Lawliet** [asagi4/comfyui-prompt-control#78]
**Describe what's missing**
After the update, something weird happened, I can't seem to get alternate loras like the legacy version did. Something like:

`<lora:LoraX:1> [<lora:LoraA:1.5>|<lora:LoraB:1>|<lora:LoraC:1>:0.1]`

I get the message that there's a lora loader for LoraX, for example, but nothing else afterwards and it seems other loras haven't been applied. Is this a new feature or it is a bug?

**Comment by asagi4** [comment]
Hmm, that definitely sounds like a bug. It should generate the necessary hooks for alternating LoRAs as well, but maybe it goes wrong there. I assume you're not using the advanced lazy lora loader with apply_hooks disabled.

I'll try to take a look later today

**Comment by asagi4** [comment]
Also please try running with `PROMPTCONTROL_DEBUG=1` in your environment, you should see some debug logging about what hook keyframes are actually being generated.

**Comment by asagi4** [comment]
I think I should aslso look into possibly attaching hooks directly on the model, if that's possible. There's a mechanism for it but I don't know if it supports scheduling like cond hooks do.

**Comment by asagi4** [comment]
You're always welcome to send bug reports, even if they turn out to be nothing in the end.

The *debug prints* did actually have a bug in them that I've fixed locally (the end keyframe shows the wrong start value), but the hooks should work correctly.

I haven't yet figured out a way to have ComfyUI tell you when it's actually applying a hook, so you just have to observe the effects. I could probably subclass some of the hooks and add my own info prints, I guess.
