### ISSUE TITLE
[Bug] Noise on empty prompt

### ISSUE THREAD

**Issue by mizukarada** [asagi4/comfyui-prompt-control#8]

**Comment by asagi4** [comment]
Can you elaborate a bit what this is about? What behaviour are you seeing and what do you think it should be?

**Comment by mizukarada** [comment]
Is this supposed to happen?:
![workflow](https://github.com/asagi4/comfyui-prompt-control/assets/111034657/6c621b1c-126f-4cf7-898e-3428e0935ea5)
top is with prompt-control, bottom is without.

**Comment by asagi4** [comment]
Hmm, I guess the scheduler might be removing the empty prompt or something. I'll have to take a look.
