### ISSUE TITLE
[BUG] Your lark package reports an ancient version (0.12.0) and will not work

### ISSUE THREAD

**Issue by ghostsquad** [asagi4/comfyui-prompt-control#81]
**Describe the bug**
Updated this node, and it's failing to import with what appears to be a misleading message:

```
Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-control module for custom nodes: Your lark package reports an ancient version (0.12.0) and will not work. If you have the 'lark-parser' package in your Python environment, remove that and *reinstall* lark!
```

except, when I look at what's installed:

```
/e/ComfyUI_windows_portable/python_embeded
$ python -m pip install --upgrade lark
Requirement already satisfied: lark in c:\python310\lib\site-packages (1.2.2)
```

```
/e/ComfyUI_windows_portable/python_embeded
$ python -m pip uninstall lark-parser
WARNING: Skipping lark-parser as it is not installed.
```

I don't know why `0.12.0` is being detected, when that's not installed. 

**To Reproduce**
Information needed to trigger the problem.
If possible, attach a workflow to reproduce the problem

**Expected behavior**
A description of what you expected to happen.

**Comment by asagi4** [comment]
Try uninstalling and reinstalling lark, or rebuilding your python environment. I have no idea what is going wrong with people's environments but this only ever seems to happen on Windows and I can't reproduce it myself.

There's a lark module in your environment somewhere that reports the wrong version, and it's known to not work like that. Unfortunately, I don't know either the cause or the exact fix.

**Comment by standwlkdljea** [comment]
This custom node seems incompatible with comfyui easy use nodes. When comfyui easy use nodes installed, this bug 100% trigger.

**Comment by asagi4** [comment]
> This custom node seems incompatible with comfyui easy use nodes. When comfyui easy use nodes installed, this bug 100% trigger.

That's a bug with the Easy use nodes then because prompt control does nothing that even can conflict anymore. It only requires a non-broken installation of lark.

**Comment by asagi4** [comment]
I guess I'll take a look at what the easy use nodes do if they trigger this, but I don't think there's anything I can do to fix this problem for people except detect it and try to give instructions for how to fix it.

**Comment by asagi4** [comment]
Ah, yeah it has lark-parser here:
https://github.com/yolain/ComfyUI-Easy-Use/blob/main/requirements.txt

That'll break things. That package is ancient and probably shouldn't be used.

**Comment by asagi4** [comment]
I created an issue here https://github.com/yolain/ComfyUI-Easy-Use/issues/595
