### ISSUE TITLE
[BUG] Lora strength changing does not work

### ISSUE THREAD

**Issue by morozig** [asagi4/comfyui-prompt-control#83]
Changing LoRA strength does not seems to work. At least with expected syntax: I'm trying to change strength from `0.9` to `1.0`, but it seems to load LoRA with double strength.
`
portrait of a woman in a garden
[<lora:flux/pony-summer-days_1101475:0.9>:<lora:flux/pony-summer-days_1101475:1.0>:0.2]
`
Maybe my syntax is incorrect?
[non-changing.json](https://github.com/user-attachments/files/18263094/non-changing.json)
[changing.json](https://github.com/user-attachments/files/18263101/changing.json)
Non changing
![non-changing](https://github.com/user-attachments/assets/e9b7681e-eb3e-4ec3-96f4-6201613a6b87)
Changing
![changing](https://github.com/user-attachments/assets/614fd452-eae4-46c8-a23e-32cbf13f1574)

**Comment by asagi4** [comment]
Can you reproduce this with non-flux models? I don't have enough VRAM to use LoRAs with flux.

Try running with debug prints enabled (set PROMPTCONTROL_DEBUG=1 in the environment) to see information about the hook schedules generated.

I'll take a look some time next week when I'm back home from holidays.

**Comment by Mossbraker** [comment]
> Can you reproduce this with non-flux models? I don't have enough VRAM to use LoRAs with flux.
> 
> Try running with debug prints enabled (set PROMPTCONTROL_DEBUG=1 in the environment) to see information about the hook schedules generated.

Result is the exact same for flux, SDXL, pony. 
```
[<lora:lora1:0.5>:0.2]
[<lora:lora2:0.15:0.25>:0.7]
[<lora:lora3:0.3>:<lora:lora3:0.45>:0.9]
```

```
[PromptControl] DEBUG: Creating hook for lora3.safetensors, weight=0.3, weight_clip=0.3
[PromptControl] DEBUG: Creating keyframe for lora3.safetensors, start=0.0
[PromptControl] DEBUG: Creating end keyframe for lora3.safetensors, start=0.2
[PromptControl] DEBUG: Creating hook for lora1.safetensors, weight=0.5, weight_clip=0.5
[PromptControl] DEBUG: Creating KF (0, 0.2) for lora1.safetensors
[PromptControl] DEBUG: Creating keyframe for lora1.safetensors, start=0.2
[PromptControl] DEBUG: Creating end keyframe for lora1.safetensors, start=0.7
[PromptControl] DEBUG: Hook already created for lora3.safetensors
[PromptControl] DEBUG: Creating keyframe for lora3.safetensors, start=0.2
[PromptControl] DEBUG: Creating end keyframe for lora3.safetensors, start=0.7
[PromptControl] DEBUG: Hook already created for lora1.safetensors
[PromptControl] DEBUG: Creating keyframe for lora1.safetensors, start=0.7
[PromptControl] DEBUG: Creating end keyframe for lora1.safetensors, start=0.9
[PromptControl] DEBUG: Creating hook for lora2.safetensors, weight=0.15, weight_clip=0.25
[PromptControl] DEBUG: Creating KF (0, 0.7) for lora2.safetensors
[PromptControl] DEBUG: Creating keyframe for lora2.safetensors, start=0.7
[PromptControl] DEBUG: Creating end keyframe for lora2.safetensors, start=0.9
[PromptControl] DEBUG: Hook already created for lora3.safetensors
[PromptControl] DEBUG: Creating keyframe for lora3.safetensors, start=0.7
[PromptControl] DEBUG: Creating end keyframe for lora3.safetensors, start=0.9
[PromptControl] DEBUG: Hook already created for lora1.safetensors
[PromptControl] DEBUG: Creating keyframe for lora1.safetensors, start=0.9
[PromptControl] DEBUG: Hook already created for lora2.safetensors
[PromptControl] DEBUG: Creating keyframe for lora2.safetensors, start=0.9
[PromptControl] DEBUG: Creating hook for lora3.safetensors, weight=0.45, weight_clip=0.45
[PromptControl] DEBUG: Creating KF (0, 0.9) for lora3.safetensors
[PromptControl] DEBUG: Creating keyframe for lora3.safetensors, start=0.9
```

**Comment by morozig** [comment]
> [<lora:lora2:0.15:0.25>:0.7]

Hey, what does this syntax mean?

**Comment by asagi4** [comment]
@morozig different weights for TE and diffusion model keys in the LoRA. Though I always forget the order of which is which... It's model weight first, TE second. If TE weight is not specificied, it uses the model weight.

**Comment by asagi4** [comment]
Hmm.

This might actually be a ComfyUI bug. As far as I can tell, the nodes are generating the correct hooks (though I did find a bug in the cache hack feature, if anyone but me was using that)

**Comment by asagi4** [comment]
Never mind, I had a silly logic error in the graph generation code. It was combining the hooks all wrong.

Can you test now if it does what you expect?

**Comment by morozig** [comment]
> Never mind, I had a silly logic error in the graph generation code. It was combining the hooks all wrong.
> 
> Can you test now if it does what you expect?

Yap, seems to be working, thanks. The issue can be closed.
![ComfyUI_00041_](https://github.com/user-attachments/assets/69fd6fea-1584-44b7-9c7b-4dadbe258b8f)
